language: python

python:
  - "3.8-dev"

services:
  - docker

before_install:
  - make compose

install:
  - make requirements-test

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script:
        - make test-cov
#    - name: "Integration Tests"
#      script:
#        - make compose

after_success:
  - codecov