language: minimal

services:
  - docker

before_install:
  - docker-compose --version

install:
  - docker-compose build
  - docker-compose up -d

script:
  - docker-compose exec grader /bin/sh -c "pip install -qr requirements/requirements-test.txt && pytest -v"