language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - docker build -t ragnaruk/external_grader .
  - docker run -idt --name external_grader ragnaruk/external_grader
  - docker ps -a

script:
  - find ./grade_scripts/ -type f -iname "*.py" -exec python -m doctest "{}" \; | grep -q "."; test $? -eq 1