language: python

python:
  - "3.8-dev"

services:
  - docker

before_install:
  - docker-compose --version
  - make compose
  - docker ps
  - docker-compose exec -it grader /bin/sh -c "make test"

install:
  - make install-test

script:
  - pytest