version: '3'
services:
  python:
    build:
      context: ./docker_images
      dockerfile: Dockerfile-python
    image: ragnaruk/python:latest
  ffmpeg:
    build:
      context: ./docker_images
      dockerfile: Dockerfile-ffmpeg
    image: ragnaruk/ffmpeg:latest
  grader-xqueue:
    build:
      context: .
    image: ragnaruk/external_grader:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./queue_configuration:/external_grader/queue_configuration
      - ./grader_scripts:/external_grader/grader_scripts
    environment:
      - QUEUE_CONFIG_NAME=stepik
    command: ['python', './external_grader/']
  grader-rabbit:
    build:
      context: .
    image: ragnaruk/external_grader:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./queue_configuration:/external_grader/queue_configuration
      - ./grader_scripts:/external_grader/grader_scripts
    environment:
      - QUEUE_CONFIG_NAME=rabbitmq_example
    command: ['python', './external_grader/']
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=jn0oSx3i2SkV5TlQAFVy