version: '3'
services:
  grader:
    build:
      context: .
      args:
        - REQUIRED_PROGRAMS=ffmpeg
    image: ragnaruk/external_grader:latest
    restart: always
    volumes:
      - ./grader_scripts:/external_grader/grader_scripts
      - ./config/:/external_grader/config/
    environment:
      # Name of the imported queue config
      # To import config_queue.rabbitmq_example.py set variable QUEUE_CONFIG_NAME=rabbitmq_example
      - QUEUE_CONFIG_NAME=rabbitmq_example
    command: ['python', '/external_grader/grader']
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=jn0oSx3i2SkV5TlQAFVy