version: '3'
services:
  python:
    build:
      context: ./docker_images
      dockerfile: Dockerfile-python
    image: ragnaruk/python:latest
  ffmpeg:
    build:
      context: ./docker_images
      dockerfile: Dockerfile-ffmpeg
    image: ragnaruk/ffmpeg:latest