HOME_PATH = "/home/box/"
VERIFICATION_FILES_PATH = "/root/"

RABBITMQ_HOST = "localhost"
RABBITMQ_PORT = 32769
RABBITMQ_CONSUMPTION_QUEUE = "student_answers"
RABBITMQ_CALLBACK_QUEUE = "student_grades"
